language: node_js
node_js:
  - v9.0.0
  - v10.23.2
  - v12.20.1
  - v14.15.4
sudo: false
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm run test
  - npm run coverage
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: ilya@doublenot.co
  api_key:
    secure: lO704xqI4qBOLbNvnY/s4dCg6IUPoCUaohCnZ6liP2xrUlk42A72nwCXUgDBmJ0qKH4DFuEA1zTxgpQkWLKDBX4ZPGNfA02sr34KeT3cMQdSAlQFYGy3xAvE+HzW0qktZzuLe9serzPiObXZr6xj8A090ST0L/2rFp7RjlC10C9mqEjRz2A7gqA6UskCqKM1isb91E5IGmyijRpt9lgkvZr8zEgLkyYvg3g5uzZmJOmoPab1sDA0WnqiXH5uUYhR7lDaZY9j3gusGSGAayM/jixwsoln0nePglaj4303yMAnYQUnUOeJ0fEX+iY3jhCzWc66A87NAAbzKVhvMfZWtn09VppE5I9vhI+c7yWuVpm9jXCgfEuOxLMVYhFNHpGe+Kj1cQa52ypneytPlsCsEVVwB8mnUBIzRaLimhS0pkqNzSYlYkEmlOJEcP2PRtWuwRyrDllT3D6jSFj5bI7d32eudRv+WldiXzOVP1gXM/isuX7DwnRPdSMDvqLUtGyDr7hwXfJOIRInZlzqVqEyyFPSY2VhqdxGAJSrYVcHtNNSJvACFEaXv+GtVHFBXBHsUOxWhf/E/Zkn7sx78ubJ+DjFfuTWch5haFaVqkshhwvalpNgIM4Pw7+BJeL47FrCZEotQ24UsWEfFzzLKpDbYXquszcHBfBYpysrPj1pYEk=
  on:
    tags: true
    repo: doublenot/refs
